### ISSUE TITLE
Is there a way to convert european unit to chinese ?

### ISSUE THREAD

**Issue by the4anoni** [aprosvetova/xiaomi-kettle#2]
Hello
I've bought european version of kette ,and i would like to convert it to chinese one ,so i can connect kette to china mainland server.
Is there a way to do this ?

**Comment by anna-oake** [comment]
I don't think it's possible until we decrypt kettle firmware. I'm sure this will not happen soon.

**Comment by the4anoni** [comment]
I think maybe this is about mac address ?
