### ISSUE TITLE
Kettle to Mqtt Bridge

### ISSUE THREAD

**Issue by SchmDan** [aprosvetova/xiaomi-kettle#7]
Hey,

you mentioned that you've build a Kettle to MQTT Bridge. Is it possible to publish your code for other using it? I would really appreciate it!

Thanks in advance!

**Comment by stek29** [comment]
Have a look at https://github.com/Hypfer/Cybele

**Comment by SchmDan** [comment]
Thanks, i will have a look at it. I haven't found this in my research.
